# Generated by Django 3.1.5 on 2021-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.AddField(
            model_name='pet',
            name='district',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
