# Generated by Django 3.1.5 on 2021-02-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to='uploaded_pet_photos'),
        ),
        migrations.CreateModel(
            name='Eu_vi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
            ],
        ),
    ]
