# Generated by Django 3.1.5 on 2021-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eu_vi',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
