# Generated by Django 3.1.5 on 2021-02-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210208_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eu_vi',
            new_name='EuVi',
        ),
        migrations.AlterModelTable(
            name='euvi',
            table='core_eu_vi',
        ),
        migrations.CreateModel(
            name='HistoriasFelizes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(default=None)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
            ],
            options={
                'db_table': 'core_historiasfelizes',
            },
        ),
    ]
