# Generated by Django 3.1.5 on 2021-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210209_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Basset', 'Basset'), ('Beagle', 'Beagle'), ('Boder Collie', 'Boder Collie'), ('Boxer', 'Boxer'), ('Buldog Francês', 'Buldog Francês'), ('Buldog Inglês', 'Bulldog Inglês'), ('Bull Terrier', 'Bull Terrier'), ('Chow-Chow', 'Chow-Chow'), ('Dachshund (Salsicha)', 'Dachshund (Salsicha)'), ('Golden', 'Golden'), ('Husky Siberiano', 'Husky Siberiano'), ('Retriever', 'Retriever'), ('Labrador', 'Labrador'), ('Lhasa Apso', 'Lhasa Apso'), ('Lulu da Pomerânia', 'Lulu da Pomerânia'), ('Maltês', 'Maltês'), ('Pastor Alemão', 'Pastor Alemão'), ('Pinscher', 'Pinscher'), ('Pit Bull', 'Pit Bull'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Schnauzer', 'Schnauzer'), ('Shih-Tzu', 'Shih-Tzu'), ('Vira-Lata(SRD)', 'Vira-Lata(SRD)'), ('Yorkshire', 'Yorkshire'), ('Outros', 'Outros')], max_length=35),
        ),
    ]
