# Generated by Django 3.1.5 on 2021-02-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210209_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriasFelizes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(default=None)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
            ],
            options={
                'db_table': 'core_historias_felizes',
            },
        ),
    ]
