# Generated by Django 3.1.5 on 2021-02-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eu_vi_house_number'),
        ('core', '0007_historiasfelizes_begin_date'),
    ]

    operations = [
    ]
