# Generated by Django 3.1.5 on 2021-02-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210211_1453'),
        ('core', '0008_merge_20210211_1603'),
    ]

    operations = [
    ]
