# Generated by Django 3.1.5 on 2021-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20210212_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiasfelizes',
            name='happyphoto',
            field=models.ImageField(default=None, upload_to='uploaded_histories_photos'),
        ),
    ]
