# Generated by Django 3.1.5 on 2021-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historiasfelizes_happyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportarPostagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_id', models.CharField(max_length=30)),
                ('pet_owner', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.IntegerField(blank=True, max_length=30)),
                ('opcao', models.CharField(choices=[('Este Animal não pertence a essa pessoa!', 'Este Animal não pertence a essa pessoa!'), ('Esse Animal já foi encontrado', 'Esse Animal já foi encontrado'), ('Essa postagem parace enganosa/fraudosa', 'Essa postagem parace enganosa/fraudosa'), ('Outro Motivo (Favor citar o motivo no campo de texto abaixo)', 'Outro Motivo (Favor citar o motivo no campo de texto abaixo)')], max_length=70)),
            ],
            options={
                'db_table': 'postagens_reportadas',
            },
        ),
    ]
