# Generated by Django 3.1.5 on 2021-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210225_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportarpostagem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
