# Generated by Django 3.1.5 on 2021-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reportarpostagem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportarpostagem',
            name='contact_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
